version: '3.8'

services:
  # Whisper Speech-to-Text Service (Faster Whisper large-v2 with CUDA)
  whisper-service:
    build:
      context: ./whisper-service
      dockerfile: Dockerfile
    ports:
      - "48.216.181.122:9000:9000"  # Whisper service port bound to public IP
    environment:
      - WHISPER_MODEL=large-v2 # Using large-v2 model for better accuracy
      - LANGUAGE=auto  # Auto-detect language or specify 'gu' for Gujarati
      - CUDA_VISIBLE_DEVICES=0  # Use first GPU if available
    volumes:
      - whisper_models:/app/models
      - ./ssl:/app/ssl:ro  # SSL certificates
    restart: unless-stopped
    # Enable GPU support for NVIDIA Docker runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s  # Allow more time for Faster Whisper model download
    networks:
      - app-network

  # Translation Service (Gujarati to English)
  translation-service:
    build:
      context: ./translation-service
      dockerfile: Dockerfile
    ports:
      - "48.216.181.122:9001:9001"  # Translation service port bound to public IP
    environment:
      - MODEL_NAME=Helsinki-NLP/opus-mt-mul-en
      - TORCH_HOME=/app/models/torch
      - TRANSFORMERS_CACHE=/app/models/transformers
    volumes:
      - translation_models:/app/models
      - ./ssl:/app/ssl:ro  # SSL certificates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s  # Allow time for model download
    networks:
      - app-network

  # Nginx Reverse Proxy with HTTPS
  nginx:
    image: nginx:alpine
    ports:
      - "48.216.181.122:443:443"  # HTTPS port
      - "48.216.181.122:80:80"    # HTTP redirect port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - whisper-service
      - translation-service
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - https

volumes:
  whisper_models:
    driver: local
  translation_models:
    driver: local

networks:
  app-network:
    driver: bridge
  default:
    name: gujarati-transcription-network
